### ISSUE TITLE
UMD release

### ISSUE THREAD

**Issue by jonataswalker** [davezuko/react-reformed#13]
Hi there, any plan to publish a UMD release?

**Comment by dvdzkwsk** [comment]
Should be pretty easy, let me see if I can get around to it today.

**Comment by jonataswalker** [comment]
Never mind, not necessary.

**Comment by dvdzkwsk** [comment]
_phew_, it was actually a little tricker than I'd hoped, so I didn't manage to get it figured out in one sitting.
