### ISSUE TITLE
Deprecation warning about PropTypes

### ISSUE THREAD

**Issue by zh217** [davezuko/react-reformed#15]
I am getting this:
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```
React version: 15.5.4

**Comment by dvdzkwsk** [comment]
I'll get any propType usage ported to the new external package when I get a minute. Thanks.

**Comment by dvdzkwsk** [comment]
Fixed with https://github.com/davezuko/react-reformed/commit/d2cca3160a835722a2ec18e0ed31f21295c84865. `v1.1.1` has been published to npm.

**Comment by BarryThePenguin** [comment]
Thanks for this! 👏😁
