### ISSUE TITLE
I implemented a reformed component in Typescript.

### ISSUE THREAD

**Issue by rluiten** [davezuko/react-reformed#19]
Thought I would share it in case anyone else might find it useful.
It did take me stubbing my toes for a good while to get things mostly ironed out.

It may still have some problems, but it is working well enough in one of my projects.
The gist with reformed.tsx https://gist.github.com/rluiten/53ff1d74b8bf5b5453990b6e2a99349e,

Thanks for your articles and example, good stuff.

**Comment by dvdzkwsk** [comment]
Very cool, thanks for taking the time to put this together. I'll probably find a place to store it as a permanent reference, but until then I'll leave this issue open for visibility for others to stumble upon.
