### ISSUE TITLE
Forms without initial model cause React warning message

### ISSUE THREAD

**Issue by branweb1** [davezuko/react-reformed#7]
Hi,
Great work on this library! I noticed a minor issue that I wanted to get your input on (no pun intended):

If you don't use an initial model for a form, React with display this error message once the `onChange` event is triggered for the first time:

```
Warning: OtherForm is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
``` 

Apparently this is caused by React treating any inputs with a value of `null` or `undefined` as uncontrolled. Typing in the input updates the model, which sets a new value on the input, converting it to controlled. 

This warning is easily avoided by just using an initial model or by doing something like `value={model.firstName || ''}`. But perhaps `bindInput` could be updated to do this by default, something like this:

```
bindInput = (name) => {
      return {
        name,
        value: this.state.model[name] || '',
        onChange: this.bindToChangeEvent,
      }
    }
```

Happy to open a PR if you think this is good idea.

**Comment by dvdzkwsk** [comment]
Ah, good catch. I end up doing this manually most of the time, mostly because not all values are strings, but this is probably the best solution given React's complaints. Ideally React would care more about the existence of a `value` prop than whether or not it was `null` or `undefined`, but c'est la vie.

Happy to accept a PR for this, and thanks for taking the time to check it out!

**Comment by branweb1** [comment]
Totally agree that's more on React than this library. Sort of a strange behavior I think. Anyway thanks for the response. PR forthcoming.
